<?php

/**
 * @file
 * RedHen customizations for the Commerce iATS payment method.
 */

/**
 * TODO: If direct post is enabled.
 *
 * Introduce new credit card payment method for RedHen.
 * Replace commerce iats credit card form so direct post fields are not used.
 * Add new submit handler to commerce iats credit card payment method.
 * On submit, collect submitted data and build new form.
 * New form consists of iats direct post form fields.
 * Populate iats direct post form field.
 * Insert javascript used to post form to iats.
 * Add callback to handle response from iats.
 * Continue donation process as usual on response from iats.
 */

/**
 * Implements hook_commerce_payment_method_info().
 */
function redhen_donation_commerce_iats_commerce_payment_method_info() {
  $payment_methods = array();

  $commerce_iats_path = drupal_get_path('module', 'commerce_iats');

  $payment_methods['redhen_iats_credit_card'] = array(
    'base' => 'redhen_donation_commerce_iats_credit_card',
    'title' => t('iATS Payments: RedHen custom credit card payment'),
    'short_title' => t('RedHen iATS credit card payment'),
    'display_title' => t('Credit card'),
    'description' => t('Integrates the iATS ProcessLink webservice width RedHen for credit card payments.'),
    'file' => $commerce_iats_path . '/includes/commerce_iats.credit_card.inc',
  );

  return $payment_methods;
}

/**
 * Payment method callback: settings form.
 */
function redhen_donation_commerce_iats_credit_card_settings_form($settings = NULL) {
  module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.credit_card');

  return commerce_iats_credit_card_settings_form_base($settings);
}

/**
 * Payment method callback: checkout form.
 */
function redhen_donation_commerce_iats_credit_card_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.credit_card');

  // Prepare the fields to include on the credit card form.
  $fields = array(
    'code' => '',
    'type' => commerce_iats_enabled_credit_card_types($payment_method),
  );

  $form = commerce_payment_credit_card_form($fields);

  if (strstr($_SERVER['HTTP_REFERER'], '/admin/')) {
    // If the form is requested via the admin panel, CVV is optional.
    $form['credit_card']['code']['#required'] = FALSE;
  }

  if (isset($payment_method['settings']['direct_post']['enable_direct_post']) && $payment_method['settings']['direct_post']['enable_direct_post'] == 1) {
    // Add empty direct post form fields.
    $form['direct_post'] = redhen_donation_commerce_iats_direct_post_form_base($payment_method);

    // Add direct post JavaScript.
    $form['#attached']['js'] = array(
      drupal_get_path('module', 'redhen_donation_commerce_iats') . '/js/redhen_donation_commerce_iats_dp.js',
    );
  }

  return $form;
}

/**
 * Payment method callback: checkout form validation.
 */
function redhen_donation_commerce_iats_credit_card_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array()) {
  module_load_include('inc', 'commerce_iats', 'includes/commerce_iats.credit_card');

  return commerce_iats_credit_card_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array());
}

/**
 * Payment method callback: checkout form submission.
 */
function redhen_donation_commerce_iats_credit_card_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
  module_load_include('inc', 'commerce_iats', 'includes/commerce_iats.credit_card');

  return commerce_iats_credit_card_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge);
}

/**
 * Returns an array of form elements common to all Direct Post forms.
 *
 * @param array $payment_method
 *   The current payment method.
 *
 * @return array
 *   Array of common Direct Post form fields.
 */
function redhen_donation_commerce_iats_direct_post_form_base($payment_method) {
  global $base_url;

  $form = array();

  // Relay URL.
  // TODO: Probably need to customize this for RedHen Donation.
  $form['iats_dpm_relay_url'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_RelayURL',
    '#default_value' => $base_url . '/commerce_iats/direct_post_relay/',
  );

  // Process Key.
  $form['iats_dpm_process_key'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_ProcessID',
    '#default_value' => $payment_method['settings']['direct_post']['process_key'],
  );

  // Total processed amount as a decimal.
  $form['iats_dpm_amount'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_Amount',
    '#default_value' => '',
  );

  // Invoice number.
  $form['iats_dpm_invoice'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_Invoice',
    '#default_value' => '',
  );

  // Store any general order information here.
  $form['iats_dpm_comment'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_Comment',
    '#default_value' => '',
  );

  // First name for the end user.
  $form['iats_dpm_first_name'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_FirstName',
    '#default_value' => '',
  );

  // Last name for the end user.
  $form['iats_dpm_last_name'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_LastName',
    '#default_value' => '',
  );

  // Address for the end user.
  $form['iats_dpm_address'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_Address',
    '#default_value' => '',
  );

  // City of the address.
  $form['iats_dpm_city'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_City',
    '#default_value' => '',
  );

  // Province of the address.
  $form['iats_dpm_province'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_Province',
    '#default_value' => '',
  );

  // Country of the address.
  $form['iats_dpm_country'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_Country',
    '#default_value' => '',
  );

  // Zip code of the address.
  $form['iats_dpm_zip_code'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_ZipCode',
    '#default_value' => '',
  );

  // Method of payment.
  $form['iats_dpm_mop'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_MOP',
    '#default_value' => '',
  );

  // Account (card) number.
  $form['iats_dpm_account_number'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_AccountNumber',
    '#default_value' => '',
  );

  // CVV2.
  $form['iats_dpm_cvv2'] = array(
    '#type' => 'hidden',
    '#name' => 'IATS_DPM_CVV2',
    '#default_value' => '',
  );

  return $form;
}
