<?php

/**
 * @file
 * RedHen customizations for the Commerce iATS payment method.
 */

/**
 * TODO:
 * Add new submit hander to commerce iats credit card payment method.
 * On submit, collect submitted data and build new form.
 * New form consists of iats direct post form fields.
 * Populate iats direct post form field.
 * Insert javascript used to post form to iats.
 * Add callback to handle response from iats.
 * Continue donation process as usual on response from iats.
 */
